"""Constants for order flow prediction."""

# Order book levels
MAX_ORDER_BOOK_LEVELS = 10
DEFAULT_TICK_SIZE = 0.01

# Feature windows (in seconds)
SHORT_WINDOW = 60
MEDIUM_WINDOW = 300
LONG_WINDOW = 900

# Model parameters
DEFAULT_BATCH_SIZE = 32
DEFAULT_LEARNING_RATE = 0.001
DEFAULT_EPOCHS = 100

# Risk management
MAX_POSITION_SIZE = 1000000
DEFAULT_STOP_LOSS = 0.02
DEFAULT_TAKE_PROFIT = 0.04
