name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  cpp-build:
    runs-on: ubuntu-latest
    continue-on-error: true  # Make C++ build optional
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}}/src/cpp

    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run C++ tests
      working-directory: ${{github.workspace}}/build
      run: |
        if [ -f CTestTestfile.cmake ]; then
          ctest -C ${{env.BUILD_TYPE}} --output-on-failure
        else
          echo "No C++ tests found, skipping"
        fi

  python-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        poetry config virtualenvs.create true
        poetry config virtualenvs.in-project true
        poetry install --no-interaction --no-ansi
        poetry run pip install types-PyYAML --no-deps || echo "Types-PyYAML installation failed, continuing..."

    - name: Run Python tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:${PWD}/src/python:${PWD}/src"
        poetry run pytest tests/

    - name: Check code formatting
      run: |
        poetry run black --check . || echo "Black formatting check failed"
        poetry run isort --check-only . || echo "isort check failed"
        poetry run flake8 . || echo "Flake8 check failed"
        poetry run mypy . || echo "Mypy check failed"

  docker:
    runs-on: ubuntu-latest
    needs: [python-build]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    continue-on-error: true

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build ML Docker image
      uses: docker/build-push-action@v4
      continue-on-error: true
      with:
        context: .
        file: ./docker/ml.Dockerfile
        push: false
        tags: order-flow-predictor-ml:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build C++ Docker image
      uses: docker/build-push-action@v4
      continue-on-error: true
      with:
        context: .
        file: ./docker/cpp.Dockerfile
        push: false
        tags: order-flow-predictor-cpp:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  performance-test:
    runs-on: ubuntu-latest
    needs: [docker]
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
    - uses: actions/checkout@v4

    - name: Run performance tests
      run: |
        # Will be implemented once performance tests are added
        echo "Performance tests will run here"
