name: Auto Label
on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Run Labeler
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        configuration-path: .github/labeler.yml
        sync-labels: true

  size-label:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Apply Size Labels
      uses: codelytv/pr-size-labeler@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        xs_label: 'size/xs'
        s_label: 'size/s'
        m_label: 'size/m'
        l_label: 'size/l'
        xl_label: 'size/xl'
        xxl_label: 'size/xxl'
        xs_max_size: '10'
        s_max_size: '30'
        m_max_size: '100'
        l_max_size: '500'
        xl_max_size: '1000'
