name: PR Quality Check

on:
  pull_request:
    branches: [ main, develop ]
    types: [opened, synchronize, reopened]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi
        poetry run pip install types-PyYAML --no-deps || echo "Types-PyYAML installation failed, continuing..."
        
    - name: Check code formatting
      run: |
        poetry run black --check .
        poetry run isort --check-only .
        
    - name: Run linting
      run: |
        poetry run flake8 .
        poetry run mypy .
        
    - name: Run tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:${PWD}/src/python:${PWD}/src"
        poetry run pytest tests/

  # Add ML model performance check if applicable
  model-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        
    - name: Install dependencies
      run: |
        poetry install --no-interaction --no-ansi
        
    - name: Run model performance tests
      run: |
        # Add your model performance validation tests here
        echo "Add model performance validation"
